### ISSUE TITLE
How to format DateTime?

### ISSUE THREAD

**Issue by RazgrizHsu** [rbatis/fastdate#3]
I would like to ask if there is a way to format as a string?
like ..
```
let now = Local::now().format( "%Y%m%d %H%M%S%.f" );
```

thanks you :)

**Comment by RazgrizHsu** [comment]
Or can you point me how can I pad 6 decimal places after nano seconds,
Because when use `format!( "{:29}", now )`
the `2022-10-24 13:22:47.977840` will be `2022-10-24 13:22:47.97784`
missing last zero 

thank you

**Comment by zhuxiujia** [comment]
> Or can you point me how can I pad 6 decimal places after nano seconds, Because when use `format!( "{:29}", now )` the `2022-10-24 13:22:47.977840` will be `2022-10-24 13:22:47.97784` missing last zero
> 
> thank you

This is a no time zone design。
format  you can use 
```rust
format!( "{}-{}-{}T{}:{}:{}", now.year,now.mon,now.day,now.hour,now.min,now.sec)
```

**Comment by RazgrizHsu** [comment]
Got it,
Thank you very much :)

zxj ***@***.***> 於 2022年10月24日 週一 13:43 寫道：
